name: Keep Replit Alive

on:
  schedule:
    - cron: '*/5 * * * *' # Cứ đúng 5 phút GitHub sẽ tự động chạy một lần
  workflow_dispatch: # Tạo nút bấm để bạn có thể tự bấm chạy thử bằng tay

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Replit Link
        run: |
          # Lệnh gọi đến link Replit của bạn để bắt nó thức dậy
          curl -I "https://89c975cf-caca-4c76-b7b1-1f019eea7db7-00-xcte5iywfmj6.pike.replit.dev/live.m3u"
